resources:
  Resources:
    # Cognito resources
    MasterUserPoolAppKeys:
      Type: 'AWS::Cognito::UserPool'
      Properties: 
        UserPoolName: ${self:service}-${self:provider.stage}-MasterUserPool-appkeys
    
    MasterResourceServerAppKeys:
      Type: AWS::Cognito::UserPoolResourceServer
      Properties: 
        Identifier: apiauthidentifier
        Name: ${self:service}-${self:provider.stage}-apiauthidentifier-appkeys
        Scopes: 
          - ScopeName: "json.read"
            ScopeDescription: json read
        UserPoolId:
          Ref: MasterUserPoolAppKeys

    MasterUserPoolClientAppKeys:
      Type: AWS::Cognito::UserPoolClient
      DependsOn: MasterResourceServerAppKeys
      Properties: 
        AllowedOAuthFlows: 
          - client_credentials 
        AllowedOAuthFlowsUserPoolClient: True
        AllowedOAuthScopes: 
          - apiauthidentifier/json.read
        # This line generates an error. The scope must be
        # activated manually in cognito after deployment
        #  - apiauthidentifier/json.read
        ClientName: ${self:service}-${self:provider.stage}-masteruserpoolclient-appkeys
        EnableTokenRevocation: True
        ExplicitAuthFlows: 
          - ALLOW_CUSTOM_AUTH
          - ALLOW_USER_SRP_AUTH
          - ALLOW_REFRESH_TOKEN_AUTH
        GenerateSecret: True
        PreventUserExistenceErrors: ENABLED
        SupportedIdentityProviders:
          - COGNITO
        UserPoolId: 
          Ref: MasterUserPoolAppKeys

    MasterDomainAppKeys:
      Type: AWS::Cognito::UserPoolDomain
      Properties: 
        Domain: ${self:service}${self:provider.stage}appkeys
        UserPoolId:
          Ref: MasterUserPoolAppKeys